mutators:
    - App\Mutators\BadgeMutator
    - App\Mutators\ImageMutator
    - App\Mutators\LocationMutator
    - App\Mutators\PathMutator
    - App\Mutators\SecurityMutator
    - App\Mutators\UserMutator
