ImageMutation:
    type: object
    config:
        description: "Allow to manage the lifecycle of an Image"
        fields:
            addImage:
                type: "Image"
                description: "Allow to create a new Image"
                args:
                    label:
                        type: "String!"
                        description: "The label of this image."
                resolve: ""
            updateImage:
                type: "Image"
                description: "Allow to update an Image"
                args:
                    label:
                        type: "String!"
                        description: ""
                resolve: ""
            deleteImage:
                type: "Image"
                description: "Allow to delete an Image"
                args:
                    id:
                        type: "Int!"
                        description: "The unique identifier of the image."
                resolve: ""
