ImageQuery:
    type: object
    config:
        description: "Allow to query a single or multiples Image(s)."
        fields:
            image:
                type: "[Image]"
                description: "Allow to fetch an Image using his identifier (not mandatory !), if omitted, all the Images are returned."
                args:
                    id:
                        type: "Int"
                        description: "The identifier of the Image"
                resolve: "@=resolver('image_resolver', [args])"
