doctrine:
    dbal:
        url: '%env(DATABASE_URL_DEV)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/mapping'
                prefix: 'App\Models'
                alias: App
