framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%locale%'
    #csrf_protection: ~
    #http_method_override: true
    #trusted_hosts: ~
    session:
        handler_id: ~
    #esi: ~
    #fragments: ~
    csrf_protection:
        enabled: true
    php_errors:
        log: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
