overblog_graphql:
    definitions:
        schema:
            badge:
                query: BadgeQuery
                mutation: BadgeMutation
            image:
                query: ImageQuery
                mutation: ImageMutation
            location:
                query: LocationQuery
                mutation: LocationMutation
            path:
                query: PathQuery
                mutation: PathMutation
            user:
                query: UserQuery
                mutation: UserMutation
        mappings:
            auto_discover: false
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~
