security:
    encoders:
        App\Interactors\UserInteractor:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: App\Interactors\UserInteractor
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout_on_user_change: true
            provider: db_provider
            form_login:
                login_path: login
                check_path: login
