security:
    providers:
        in_memory: { memory: ~ }

    encoders:
        App\Models\User:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout_on_user_change: true
            form_login:
                login_path: /login
                check_path: login
