apiVersion: v1
kind: Service
metadata:
  name: cyclepath-main
  labels:
    app: cyclepath
    tier: main
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: cyclepath
    tier: main
