apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cyclepath-main
  labels:
    app: cyclepath
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: cyclepath
        tier: main
    spec:
      containers:
      - name: cyclepath-app
        image: gcr.io/guillaume-190508/cyclepath_main
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
