apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: cyclepath-frontend
    tier: frontend
spec:
  # type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: cyclepath
    tier: frontend
