UserQuery:
    type: object
    config:
        description: "Allow to query an user."
        fields:
            user:
                type: "[User]"
                description: "Allow to fetch an User using his identifier (not mandatory !), if omitted, all the Users are returned."
                args:
                    id:
                        type: "Int"
                        description: "The identifier of the User"
                resolve: "@=resolver('user_resolver', [args])"
