Mutation:
    type: object
    config:
        description: "Allow to create, update, delete entities and use Security"
        fields:
            # Security
            registerUser:
                type: "User"
                description: "Allow to register a new user."
                args:
                    email:
                        type: "String"
                        description: "The email of the user."
                    username:
                        type: "String"
                        description: "The username of the user."
                    password:
                        type: "String"
                        description: "The password of the user."
                resolve: "@=service('SecurityMutator'.register(args)"
            validateUser:
                type: "User"
                description: "Allow to validate a recent User."
                args:
                    email:
                        type: "String!"
                        description: "The email of the User who ask for validation."
                    validationToken:
                        type: "String!"
                        description: "The validation Token send by email."
                resolve: "@=service('SecurityMutator').validate(args)"
            login:
                type: "User"
                description: "Allow to log an User"
                args:
                    email:
                        type: "String!"
                        description: "The user email linked to his profile."
                    password:
                        type: "String!"
                        description: "The user password (in clear version !) linked to his email."
                resolve: "@=service('SecurityMutator').login(args)"
            forgot_password:
                type: "User"
                description: "Allow to reset the password of an User"
                args:
                    email:
                        type: "String!"
                        description: "The email linked to this user."
                    username:
                        type: "String!"
                        description: "The username linked to his email."
                resolve: "@=service('SecurityMutator').forgotPassword(args)"
            reset_password:
                type: "User"
                description: "Allow to hard reset the password of an User"
                args:
                    email:
                        type: "String!"
                        description: "The email linked to this user."
                    resetToken:
                        type: "String!"
                        description: "The reset token received via the forgot password request."
                    password:
                        type: "String!"
                        description: "The email linked to this user."
                resolve: "@=service('SecurityMutator').resetPassword(args)"

            # Badge
            createBadge:
                type: "Badge"
                description: "Allow to create a new Badge."
                args:
                    label:
                        type: "String!"
                        description: "The label of the Badge."
                    level:
                        type: "Int!"
                        description: "The level of the Badge."
                resolve: "@=service('BadgeMutator').createBadge(args)"
            updateBadge:
                type: "Badge"
                description: "Allow to update a Badge."
                args:
                    id:
                        type: "Int!"
                        description: "The unique identifier of the Badge"
                    label:
                        type: "String"
                        description: "The new label of the Badge."
                    level:
                        type: "Int"
                        description: "The new level of the Badge."
                resolve: "@=service('BadgeMutator').updateBadge(args)"
            removeBadge:
                type: "Badge"
                description: "Allow to delete a Badge."
                args:
                    id:
                        type: "Int!"
                        description: "The unique identifier of the Badge."
                    userId:
                        type: "Int"
                        description: "The unique identifier of the user who own the Badge."
                resolve: "@=service('BadgeMutator').removeBadge(args)"

            # Image
            createImage:
                type: "Image"
                description: "Allow to create a new Image."
                args:
                    label:
                        type: "String!"
                        description: "The label of the Image."
                    alt:
                        type: "String!"
                        description: "The replacement text of the Image."
                    user:
                        type: "Int"
                        description: "The unique identifier of the user who own the Image."
                resolve: ""
            updateImage:
                type: "Image"
                description: "Allow to update an Image"
                args:
                    id:
                        type: "Int!"
                        description: "The unique identifier of the Image."
                    label:
                        type: "String"
                        description: "The label of the image."
                    alt:
                        type: "String"
                        description: "The replacement text of the image."
                resolve: ""
            deleteImage:
                type: "Image"
                description: "Allow to delete a single image."
                args:
                    email:
                        type: "Int!"
                        description: "The unique identifier of the image."
                resolve: "@=service('ImageMutator').removeImage(args)"

            # Location
            addLocation:
                type: "Location"
                description: "Allow to add a Location to a Path"
                args:
                    pathId:
                        type: "Int!"
                        description: "The unique identifier of the Path who own the Location"
                    timestamp:
                        type: "Int!"
                        description: "The timestamp of the location."
                    latitude:
                        type: "Float!"
                        description: "The latitude of the location."
                    longitude:
                        type: "Float!"
                        description: "The longitude of the location."
                    altitude:
                        type: "Float"
                        description: "The altitude of the location."
                resolve: "@=service('LocationMutator').addLocation(args)"
            removeLocations:
                type: "Location"
                description: "Allow to remove all the locations linked to a Path"
                args:
                    pathId:
                        type: "Int!"
                        description: "The unique identifier of the Path who own the Location"
                resolve: "@=service('LocationMutator').removeLocation(args)"

            # Path
            createPath:
                type: "Path"
                description: "Allow to create a new Path"
                args:
                    startingDate:
                        type: "String!"
                        description: "The starting date of this path"
                    endingDate:
                        type: "String!"
                        description: "The ending date of this path"
                    distance:
                        type: "Float!"
                        description: "The distance of this path"
                    altitude:
                        type: "Float"
                        description: "The average altitude of this path"
                    favorite:
                        type: "Boolean!"
                        description: "If the path is a favorite one"
                resolve: "@=service('PathMutator').createPath(args)"
            updatePath:
                type: "Path"
                description: "Allow to update a Path"
                args:
                    favorite:
                        type: "Float!"
                        description: "If the path is a favorite one"
                resolve: "@=service('PathMutator').updatePath(args)"
            removePath:
                type: "Path"
                description: "Allow to remove a Path"
                args:
                    id:
                        type: "Int!"
                        description: "The unique identifier of the Path"
                resolve: "@=service('PathMutator').removePath(args)"

            # User
            updateUser:
                type: "User"
                description: "Allow to update the profile of an User"
                args:
                    firstname:
                        type: "String"
                        description: "The firstname of the User"
                    lastname:
                        type: "String"
                        description: "The lastname of the User"
                    username:
                        type: "String"
                        description: "The username of the User"
                    email:
                        type: "String"
                        description: "The email of the User"
                    roles:
                        type: "String"
                        description: "The role of the User"
                resolve: "@=service('UserMutator').updateUser(args)"
            removeUser:
                type: "User"
                description: "Allow to delete an User"
                args:
                    id:
                        type: "Int!"
                        description: "The unique identifier of the User"
                resolve: "@=service('UserMutator').removeUser(args)"
