version: 2
jobs:
   phpspec:
       docker:
           - image: circleci/php:7.1-fpm
       steps:
           - checkout
           - run: sudo composer self-update
           - restore_cache:
               keys:
                   - composer-v1-{{ checksum "composer.json" }}
                   - composer-v1-
           - run: composer install -n
           - save_cache:
               key: composer-v1-{{ checksum "composer.json" }}
               paths:
                   - vendor
           - run: cp .env.dist .env
           - run: vendor/bin/phpspec run
   phpunit:
         docker:
             - image: circleci/php:7.1-fpm
         steps:
             - checkout
             - run: sudo composer self-update
             - restore_cache:
                 keys:
                     - composer-v1-{{ checksum "composer.json" }}
                     - composer-v1-
             - run: composer install -n --optimize-autoloader --apcu-autoloader
             - run: composer dump-autoload --optimize --apcu
             - save_cache:
                 key: composer-v1-{{ checksum "composer.json" }}
                 paths:
                     - vendor
             - run: cp .env.dist .env
             - run: ./bin/console d:d:c --env=test
             - run: ./bin/console d:s:c --env=test
             - run: vendor/bin/phpunit -v
   behat:
       docker:
           - image: circleci/php:7.1-node-browsers
       steps:
           - checkout
           - run: sudo composer self-update
           - restore_cache:
               keys:
                   - composer-v1-{{ checksum "composer.json" }}
                   - composer-v1-
           - run: composer install -n
           - save_cache:
               key: composer-v1-{{ checksum "composer.json" }}
               paths:
                   - vendor
           - run: cp .env.dist .env
           - run:
               name: Installing Docker-compose
               command: |
                       curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
                       chmod +x ~/docker-compose
                       sudo mv ~/docker-compose /usr/local/bin/docker-compose
           - run: sudo yarn upgrade
           - run: yarn install
           - save_cache:
               key: node-v1-{{ checksum "package.json" }}
               paths:
                   - node_modules
           - run: ./node_modules/.bin/encore production
           - run: cp .env.dist .env
           - run: ./bin/console d:d:c --env=test
           - run: ./bin/console d:s:c --env=test
           - run: vendor/bin/behat
   blackfire-player:
       docker:
           - image: circleci/php:7.1-fpm-browsers
       steps:
           - checkout
           - run: sudo curl -OLsS http://get.blackfire.io/blackfire-player.phar
           - run: sudo chmod +x blackfire-player.phar
           - run: sudo mv blackfire-player.phar /usr/local/bin/blackfire-player
           - run: sudo blackfire-player run scenarios/dev.bkf --variable env=http://127.0.0.1:8000/ --full-report -v
   encore:
         docker:
             - image: circleci/node:7.10.0
         steps:
             - checkout
             - run: sudo yarn upgrade
             - run: yarn install
             - save_cache:
                 key: node-v1-{{ checksum "package.json" }}
                 paths:
                     - node_modules
             - run: ./node_modules/.bin/encore production
workflows:
    version: 2
    unit_and_spec:
        jobs:
            - phpspec
            - phpunit
            - behat
            - blackfire-player
    frontend:
        jobs:
            - encore
