PathMutation:
    type: object
    config:
        description: "Allow to manage the Path lifecycle."
        fields:
            createPath:
                type: "Path"
                description: "Allow to save a new Path."
                args:
                    startingDate:
                        type: "String!"
                        description: "The starting date of the Path"
                    endingDate:
                        type: "String!"
                        description: "The ending date of the Path"
                    distance:
                        type: "Int!"
                        description: "The distance of the Path"
                    altitude:
                        type: "Float!"
                        description: "The average altitude."
                    favorite:
                        type: "Boolean!"
                        description: "If the path is a favorite one"
                resolve: ""
