Query:
    type: object
    config:
        description: ""
        fields:
            image:
                type: "[Image]"
                description: ""
                args:
                    id:
                        type: "Int"
                        description: "The identifier of the Image"
                resolve: "@=resolver('image_resolver', [args])"
            user:
                type: "[User]"
                args:
                    id:
                        type: "Int"
                        description: "The identifier of the Image"
                    username:
                        type: "String"
                        description: "The username of the User"
                    email:
                        type: "String"
                        description: "The email of the User"
                resolve: ""
            badge:
                type: "[Badge]"
                args:
                    id:
                        type: "Int"
                        description: "The identifier of the Badge"
                    label:
                        type: "String"
                        description: "The name of the Badge"
                resolve: "@=resolver('badge_resolver', [args])"
            path:
                type: "[Path]"
                args:
                    id:
                        type: "Int"
                        description: "The identifier of the Path"
                    duration:
                        type: "String"
                        description: "The duration of the Path"
                    distance:
                        type: "String"
                        description: "The distance of the Path"
                    altitude:
                        type: "String"
                        description: "The medium altitude of the Path"
                resolve: ""
            location:
                type: "[Location]"
                args:
                    id:
                        type: "Int"
                        description: "The identifier of the Location"
                resolve: ""
