Query:
    type: object
    config:
        description: ""
        fields:
            image:
                type: "[Image]"
                description: ""
                args:
                    id:
                        type: "Int"
                        description: "The identifier of the Image"
                resolve: "@=resolver('image_resolver', [args])"
            user:
                type: "[User]"
                args:
                    id:
                        type: "Int"
                        description: "The identifier of the Image"
                resolve: "@=resolver('user_resolver', [args])"
            badge:
                type: "[Badge]"
                args:
                    id:
                        type: "Int"
                        description: "The identifier of the Badge"
                resolve: "@=resolver('badge_resolver', [args])"
            path:
                type: "[Path]"
                args:
                    id:
                        type: "Int"
                        description: "The identifier of the Path"
                resolve: "@=resolver('path_resolver', [args])"
            location:
                type: "[Location]"
                args:
                    id:
                        type: "Int"
                        description: "The identifier of the Location"
                resolve: "@=resolver('location_resolver', [args])"
