index:
    path: /
    methods: ["GET"]
    defaults: { _controller: App\Action\HomeAction }

administration_home:
    path:    /administration
    methods: ["GET"]
    defaults: { _controller: App\Action\Administration\HomeAction }
