root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: 'index'
        permanent: true

index:
    path: /{_locale}/
    methods: ["GET"]
    defaults:
        _controller: App\Action\HomeAction
    requirements:
        _locale: '%locale%'

administration_home:
    path:    /{_locale}/administration
    methods: ["GET"]
    defaults: { _controller: App\Action\Administration\HomeAction }

register:
    path: /{_locale}/register
    methods: ['GET', 'POST']
    defaults:
        _controller: App\Action\Security\RegisterAction

login:
    path: /{_locale}/login
    methods: ['GET', 'POST']
    defaults:
        _controller: App\Action\Security\LoginAction

validation:
    path: /{_locale}/validation/{userEmail}/{validationToken}
    methods: ['GET']
    defaults:
        _controller: App\Action\Security\ValidationTokenAction
    requirements:
        userEmail: '\S+'
        validationToken: '\S+'
