root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: 'index'
        permanent: true

index:
    path: /{_locale}/
    methods: ["GET", "POST"]
    defaults:
        _controller: App\Action\HomeAction
    requirements:
        _locale: '%locale%'

register:
    path: /{_locale}/register
    methods: ['GET', 'POST']
    defaults:
        _controller: App\Action\Security\RegisterAction
    requirements:
        _locale: '%locale%'

login:
    path: /{_locale}/login
    methods: ['GET', 'POST']
    defaults:
        _controller: App\Action\Security\LoginAction
    requirements:
        _locale: '%locale%'

logout:
    path: /logout

validation:
    path: /{_locale}/validation/{userEmail}/{validationToken}
    methods: ['GET']
    defaults:
        _controller: App\Action\Security\ValidationTokenAction
    requirements:
        userEmail: '\S+'
        validationToken: '\S+'

paths_list:
    path:    /paths
    methods: ["GET"]
    defaults:
        _controller: App\Action\Paths\PathsHomeAction

dashboard_home:
    path:    /{_locale}/dashboard
    methods: ["GET"]
    defaults:
        _controller: App\Action\Dashboard\DashboardHomeAction
    requirements:
        _locale: '%locale%'
