root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: 'index'
        permanent: true

index:
    path: /{_locale}/
    methods: ["GET", "POST"]
    defaults:
        _controller: App\Action\Core\HomeAction
    requirements:
        _locale: '%locale%'

contact:
    path: /{_locale}/contact
    methods: ['GET', 'POST']
    defaults:
        _controller: App\Action\Core\ContactAction

paths_list:
    path:    /{_locale}/paths
    methods: ["GET"]
    defaults:
        _controller: App\Action\Paths\PathsHomeAction

security:
    resource: 'routes/security/security.yaml'

dashboard:
    resource: 'routes/dashboard/dashboard.yaml'
