parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Builders\:
        resource: '../src/Builders'

    graphql.badge_resolver:
        class: App\Resolvers\BadgeResolver
        tags:
            - { name: overblog_graphql.resolver, alias: 'badge_resolver', method: getBadges }

    graphql.image_resolver:
        class: App\Resolvers\ImageResolver
        tags:
            - { name: overblog_graphql.resolver, alias: 'image_resolver', method: getImages }

    graphql.location_resolver:
        class: App\Resolvers\LocationResolver
        tags:
            - { name: overblog_graphql.resolver, alias: 'location_resolver', method: getLocations }

    graphql.path_resolver:
        class: App\Resolvers\PathResolver
        tags:
            - { name: overblog_graphql.resolver, alias: 'path_resolver', method: getPaths }

    graphql.user_resolver:
        class: App\Resolvers\UserResolver
        tags:
            - { name: overblog_graphql.resolver, alias: 'user_resolver', method: getUsers }

    graphql.security_mutator:
        class: App\Mutators\SecurityMutator
        tags:
            - { name: overblog_graphql.mutation, alias: 'register_mutator', method: registerUser }
            - { name: overblog_graphql.mutation, alias: 'login_mutator', method: loginUser }
