parameters:
    locale: 'fr'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DataFixtures,Exceptions,Gateway,Migrations,Models,Repository}'

    App\Action\:
        resource: '../src/Action'
        tags: ['controller.service_arguments']
