LocationQuery:
    type: object
    config:
        description: "Alloow to query one or multiples location(s)."
        fields:
            location:
                type: "[Location]"
                description: "Allow to fetch a Location using his identifier (not mandatory !), if omitted, all the Locations are returned."
                args:
                    id:
                        type: "Int"
                        description: "The identifier of the Location"
                resolve: "@=resolver('location_resolver', [args])"
