LocationMutation:
    type: object
    config:
        description:
        fields:
            addLocation:
                type: "Location"
                description: ""
                args:
                    latitude:
                        type: "Float!"
                        description: ""
                    longitude:
                        type: "Float!"
                        description: ""
                resolve: ""
