register:
    path: /{_locale}/register
    methods: ['GET', 'POST']
    defaults:
        _controller: App\Action\Security\RegisterAction
    requirements:
        _locale: '%locale%'

login:
    path: /{_locale}/login
    methods: ['GET', 'POST']
    defaults:
        _controller: App\Action\Security\LoginAction
    requirements:
        _locale: '%locale%'

logout:
    path: /{_locale}logout

account_validation:
    path: /{_locale}/validation/{userEmail}/{validationToken}
    methods: ['GET']
    defaults:
        _controller: App\Action\Security\ValidationTokenAction
    requirements:
        userEmail: '\S+'
        validationToken: '\S+'

reset_password_ask:
    path: /{_locale}/reset/password
    methods: ['GET', 'POST']
    defaults:
        _controller: App\Action\Security\ResetPasswordAskAction
    requirements:
        token: '\S+'

reset_password:
    path: /{_locale}/reset-password/{token}
    methods: ['GET', 'POST']
    defaults:
        _controller: App\Action\Security\ResetPasswordAction
    requirements:
        token: '\S+'
