App\Models\Badge:
    type: entity
    table: cyclepath_badge
    repositoryClass: App\Repository\BadgeRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        label:
            type: string
            length: 100
            nullable: false
        obtentionDate:
            type: datetime
            nullable: false
        level:
            type: integer
            nullable: false

    oneToOne:
        image:
            targetEntity: App\Models\Image
            inversedBy: badge

    manyToOne:
        user:
            targetEntity: App\Models\User
            inversedBy: badges
