App\Interactors\UserInteractor:
    type: entity
    table: cyclepath_user
    repositoryClass: App\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 50
            nullable: true
        lastname:
            type: string
            length: 50
            nullable: true
        username:
            type: string
            length: 75
            unique: true
            nullable: false
        email:
            type: string
            length: 150
            unique: true
            nullable: false
        password:
            type: string
            length: 60
            nullable: false
        roles:
            type: array
            nullable: false
        creationDate:
            type: datetime
            nullable: false
        validationDate:
            type: datetime
            nullable: true
        validated:
            type: boolean
            nullable: false
        active:
            type: boolean
            nullable: false
        apiToken:
            type: text
            length: 350
            nullable: true
        validationToken:
            type: string
            length: 255
            nullable: false
        resetToken:
            type: string
            length: 125
            nullable: true

    oneToOne:
        image:
            targetEntity: App\Interactors\ImageInteractor
            inversedBy: user
            cascade: ["persist", "remove"]

    oneToMany:
        paths:
            targetEntity: App\Interactors\PathInteractor
            mappedBy: user
            cascade: ["persist", "remove"]
        badges:
            targetEntity: App\Interactors\BadgeInteractor
            mappedBy: user
